readymade_oatmeal/closet/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = "closet"

urlpatterns = [
	path('', views.closet, name="closet"),
	path('closet2/', views.closet2, name="closet2"),
	path('ootd/', views.ootdview, name="ootd"),
	path('clear/', views.clear_database, name='clear_database'),
	path('basic-upload/', views.BasicUploadView.as_view(), name='basic_upload'),
	path('<int:pk>/', views.DetailView.as_view(), name="detail"),
	path('new/', views.clothes_reg, name='new'),
]

readymade_oatmeal/readymade_oatmeal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeView.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('closet/', include('closet.urls')),
]


urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

readymade_oatmeal/closet/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField


# Create your models here.

CATEGORY_CHOICES = (
	('coat', 'coat'),
	('jacket', 'jacket'),
	('blazer', 'blazer'),
	('vest', 'vest'),
	('dress', 'dress'),
	('jumpsuit', 'jumpsuit'),
	('shirt/blouse', 'shirt/blouse'),
	('t-shirt', 't-shirt'),
	('tank top', 'tank top'),
	('bodysuit', 'bodysuit'),
	('sweatshirt', 'sweatshirt'),
	('sweater', 'sweater'),
	('cardigan', 'cardigan'),
	('pants', 'pants'),
	('jeans', 'jeans'),
	('leggings', 'leggings'),
	('shorts', 'shorts'),
	('skirt', 'skirt'),
	('shoes', 'shoes'),
	('bag', 'bag'),
	('accessory', 'accessory'),
	('etc', 'etc'),
)

SEASON_CHOICES = (
	('spring', 'spring'),
	('summer', 'summer'),
	('fall', 'fall'),
	('winter', 'winter'),
	('etc', 'etc'),
)

COLOR_CHOICES = (
	('black', 'black'),
	('grey', 'grey'),
	('white', 'white'),
	('beige', 'beige'),
	('brown', 'brown'),
	('metallic', 'metallic'),
	('purple', 'purple'),
	('blue', 'blue'),
	('green', 'green'),
	('yellow', 'yellow'),
	('orange', 'orange'),
	('pink', 'pink'),
	('off-white', 'off-white'),
	('red', 'red'),
	('neon', 'neon'),
	('etc', 'etc'),
)

PATTERN_CHOICES = (
	('animal print', 'animal print'),
	('camouflage', 'camouflage'),
	('floral', 'floral'),
	('gingham', 'gingham'),
	('plaid', 'plaid'),
	('polka dot', 'polka dot'),
	('solid', 'solid'),
	('striped', 'striped'),
)


class Photo(models.Model):
	file = models.ImageField(width_field='width_field', height_field='height_field', blank=True, null=True, upload_to="temp/", )
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)


class Clothes(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title = models.CharField(max_length=255, default="")
	#description = models.CharField(max_length=255, default="")
	category = MultiSelectField(choices=CATEGORY_CHOICES)
	season = MultiSelectField(choices=SEASON_CHOICES)
	color = MultiSelectField(choices=COLOR_CHOICES)
	pattern = MultiSelectField(choices=PATTERN_CHOICES)
	photoid = models.IntegerField(default=0)
	photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name="image")
	created_at = models.DateTimeField(auto_now_add=True)


	def get_absolute_url(self):
		return reverse('closet:detail', kwargs={"pk":self.id})

readymade_oatmeal/closet/forms.py
from django import forms
from django.shortcuts import get_object_or_404
#from crispy_forms.helper import FormHelper
from . import models


class PhotoForm(forms.ModelForm):
	class Meta:
		model = models.Photo
		fields = [
			'file',
		]


class ClothesForm(forms.ModelForm):
	class Meta:
		model = models.Clothes
		fields = [
			'category', 
			'season', 
			'color', 
			'pattern',
			'photoid',
		]




 
 
class TestForm(forms.Form):
    """
    Form to upload the screenshot of a webpage
    """
 
    image_data = forms.CharField(widget=forms.HiddenInput(), required=False)
 
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = "agreement_form"
        self.helper.form_method = 'post'
 
        super(TestForm, self).__init__(*args, **kwargs)

Clothes_Formset = forms.modelformset_factory(
	models.Clothes, 
	form=ClothesForm
)

readymade_oatmeal/closet/views.py
import time
from django.views import View, generic
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.http import JsonResponse
from django.db.models import Q
from django.urls import reverse
import json
from django.core import serializers
from . import models
from . import forms
from django.forms import modelformset_factory
# Create your views here.

'''
class ClothesRegisterView(generic.CreateView):
	form_class = forms.ClothesForm
	template_name = 'closet/clothes_form.html'


	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.title = self.object.color + self.object.category
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())
'''


@login_required(login_url='/accounts/login/')
def clothes_reg(request):
	'''
		Clothing registration page. Need login to hop in
	'''
	form = forms.ClothesForm()
	formset = forms.Clothes_Formset(queryset=models.Clothes.objects.none())
	if request.method == 'POST':
		formset = forms.Clothes_Formset(request.POST, request.FILES, queryset=models.Clothes.objects.none())
		if formset.is_valid():
			clothes = formset.save(commit=False)
			for piece in clothes:
				piece.user = request.user
				piece.photo = get_object_or_404(models.Photo, pk=piece.photoid)
				piece.save()
			return HttpResponseRedirect(reverse('closet:closet'))
	return render(request, 'closet/clothes_form.html', {'formset':formset})


@login_required(login_url='/accounts/login/')
def closet(request):
	'''
		Closet main first page for registered clothes for each user...
	'''
	form = forms.ClothesForm()
	closet = models.Clothes.objects.filter(user=request.user)
	return render(request, "closet/closet.html", {'form':form, 'closet':closet})


@login_required(login_url='/accounts/login/')
def closet2(request):
	cg_list = request.GET.getlist('cg_checked', None)
	ss_list = request.GET.getlist('ss_checked', None)
	co_list = request.GET.getlist('co_checked', None)
	pt_list = request.GET.getlist('pt_checked', None)
	q_objects1 = Q()
	q_objects2 = Q()
	q_objects3 = Q()
	q_objects4 = Q()

	if cg_list:
		for item in cg_list:
			q_objects1.add(Q(category__icontains=item), Q.OR)
		closet2 = models.Clothes.objects.filter(q_objects1)
	if ss_list:
		for item in ss_list:
			q_objects2.add(Q(season__icontains=item), Q.OR)
	if co_list:
		for item in co_list:
			q_objects3.add(Q(color__icontains=item), Q.OR)
	if pt_list:
		for item in pt_list:
			q_objects4.add(Q(pattern__icontains=item), Q.OR)

	closet = models.Clothes.objects.filter(q_objects1).filter(q_objects2).filter(q_objects3).filter(q_objects4)
	data = closet.values('id', 'photo')
	#data = serializers.serialize('json', closet)	
	#print(data)
	response = json.dumps(list(data))
	return JsonResponse(response, safe=False)


def ootdview(request):
	form = forms.ClothesForm()
	clothes = models.Clothes.objects.all()
	return render(request, 'closet/ootd.html', {'form':form, 'clothes':clothes})


class ClosetView(generic.ListView):
	model = models.Clothes
	context_object_name="closet"
	template_name = "closet/closet.html"

	def get_queryset(self):
		if not self.request.user.is_superuser:
			return self.model.objects.filter(user=self.request.user)
		return self.model.objects.all()


class DetailView(generic.DetailView):
	model = models.Clothes
	template_name = "closet/clothes_info.html"


class BasicUploadView(View):
    def get(self, request):
        photos_list = models.Photo.objects.all()
        return render(self.request, 'photos/basic_upload/index.html', {'photos': photos_list})

    def post(self, request):
        form = forms.PhotoForm(self.request.POST, self.request.FILES)
        print("here1")
        if form.is_valid():
            photo = form.save()
            print("did it add?")
            data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url, 'photo_id': photo.id}
        else:
        	print("it's here")
        	data = {'is_valid': False}
        return JsonResponse(data)


def clear_database(request):
	'''
		Delete the data that users don't want anymore
	'''
	for photo in Photo.objects.all():
		photo.file.delete()
		photo.delete()
	return redirect(request.POST.get('next'))

readymade_oatmeal/closet/templates/closet/closet.html
{% extends "layout.html" %}

{% load static from staticfiles %}
{% block static %}<link rel="stylesheet" href="{% static 'closet/css/basic.css' %}">{% endblock %}
{% block title %}closet|{{ block.super }}{% endblock %}

  
{% block content %} 
<div class="sidenavigation">
	<button class="accordion">Category</button>
	<div class="panel">
		{{ form.category }}
	</div>
	<button class="accordion">Season</button>
	<div class="panel">
		{{ form.season }}
	</div>
	<button class="accordion">Color</button>
	<div class="panel">
		{{ form.color }}
	</div>
	<button class="accordion">Pattern</button>
	<div class="panel">
		{{ form.pattern }}
	</div>
</div>
<div>
	<input type="search" name="q"></p>
	<input type="button" name="search" value="search">
	{% for clothes in closet %}
		<p><a href="{% url 'closet:detail' pk=clothes.pk %}"><img src='{{ clothes.photo.file.url }}'/ width="300" height="400"></a></p>
	{% endfor %}

</div>
<div id="results">
	
</div>

{% endblock %}


{% block javascript %}
<script>
	jQuery.ajaxSettings.traditional = true;
	var cg_checked = [];
	var ss_checked = [];
	var co_checked = [];
	var pt_checked = [];
	//dkdkd
	$("#id_category input:checkbox").change(function () {
 		if(this.checked){
 			cg_checked.push(this.value)
 			console.log(cg_checked) 			
 		}

 		if(!(this.checked)){
 			cg_checked.splice(cg_checked.indexOf(this.value),1); 
 			console.log(cg_checked)
 		}
 		$.ajax({
	 		url: '{% url "closet:closet2" %}',
	 		data: {
	 			'cg_checked': cg_checked, 'ss_checked':ss_checked, 'co_checked':co_checked, 'pt_checked':pt_checked
	 		},
	 		dataType: 'json',
	 		success: function (response) {
	 			var html = "<ul>"
	 			var json_data = JSON.parse(response);
	 			for (var i = 0; i < json_data.length; i++) {
				    obj = json_data[i];
				    console.log(obj)
				    html += "<img src=";
				    html += obj["photo"]
				    html += "/>";
			  	}
				html += "</ul>";
				$("#results").html(html);
	 		}
 		});
 	});
 	$("#id_season input:checkbox").change(function () {
 		if(this.checked){
 			ss_checked.push(this.value)
 			console.log(ss_checked)
 		}
 		if(!(this.checked)){
 			ss_checked.splice(ss_checked.indexOf(this.value),1); 
 			console.log(ss_checked)
 		}
 		$.ajax({
	 		url: '{% url "closet:closet2" %}',
	 		data: {
	 			'cg_checked': cg_checked, 'ss_checked':ss_checked, 'co_checked':co_checked, 'pt_checked':pt_checked
	 		},
	 		dataType: 'json',
	 		success: function (data) {
				console.log(data)
	 		}
 		});
 	});
 	$("#id_color input:checkbox").change(function () {
 		if(this.checked){
 			co_checked.push(this.value)
 			console.log(co_checked)
 		}
 		if(!(this.checked)){
 			co_checked.splice(co_checked.indexOf(this.value),1); 
 			console.log(co_checked)
 		}
 		$.ajax({
	 		url: '{% url "closet:closet2" %}',
	 		data: {
	 			'cg_checked': cg_checked, 'ss_checked':ss_checked, 'co_checked':co_checked, 'pt_checked':pt_checked
	 		},
	 		dataType: 'json',
	 		success: function (data) {
				console.log("succccs")
				console.log(data)
	 		}
 		});
 	});
 	$("#id_pattern input:checkbox").change(function () {
 		if(this.checked){
 			pt_checked.push(this.value)
 			console.log(pt_checked)
 		}
 		if(!(this.checked)){
 			pt_checked.splice(pt_checked.indexOf(this.value),1); 
 			console.log(pt_checked)
 		}
 		$.ajax({
	 		url: '{% url "closet:closet2" %}',
	 		data: {
	 			'cg_checked': cg_checked, 'ss_checked':ss_checked, 'co_checked':co_checked, 'pt_checked':pt_checked
	 		},
	 		dataType: 'json',
	 		success: function (data) {
				console.log("succccs")
				console.log(data)
	 		}
 		});
 	});
</script>
<script src="{% static 'closet/js/closet.js' %}"></script>
{% endblock %}

readymade_oatmeal/closet/templates/closet/clothes_form.html
{% extends 'layout.html' %}

{% load static %}


{% block title %}Add Your Clothes|{{ block.super }}{% endblock %}

{% block content %}
<div>
	<form method="POST" enctype="multipart/form-data" id="ultimate_form">
		{% csrf_token %}
		{{ formset.management_form }}
		<div id="form_set" class="add_more" style="visibility:hidden">
	    {% for form in formset.forms %}
	        <table class='no_error'>
	            {{ form.as_table }}
	        </table>
	    {% endfor %}
		</div>
		<hr>
		<input type="submit" value="SUBMIT">
	</form>
</div>

<div id="empty_form" style="display:none">
    <table class='no_error'>
        {{ formset.empty_form.as_table }}
    </table>
</div>

<div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
    </button>
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'closet:basic_upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
</div>

  <table id="gallery" class="table table-bordered" style="display:none">
    <thead>
      <tr>
        <th>Photo</th>
      </tr>
    </thead>
    <tbody>
      {% for photo in photos %}
        <tr>
          <!--<td><a href="{{ photo.image.url }}"><img src="{{ photo.image.url }}" /></a></td>-->
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}


{% block javascript %}
<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>
<script>
var img_section;
var url_list = [];
var id_list = [];
var photo_ids = [];
var num = 0

	$('.js-upload-photos').click(function(){
		$("#fileupload").click();
		$("#fileupload").on('change', function(e){
			var file_len = e.target.files.length;
			$('#form_set').attr("style", "visibility: block")
			photo_ids.push($("#id_form-0-photoid"));
			for(let i=0; i<file_len-1; i++){
				var form_idx = $('#id_form-TOTAL_FORMS').val();
				$('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
				$('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
				photo_ids.push($("#id_form-"+(i+1)+"-photoid"));
				console.log("kjk3")
			}
			img_section = $(".no_error tbody");
		});
		$("#fileupload").fileupload({
			dataType: 'json',
			done: function (e, data) {
				if (data.result.is_valid) {
					url_list.push(data.result.url);
					id_list.push(data.result.photo_id);
					photo_ids[num].val(data.result.photo_id);
					console.log(photo_ids[num].val())
					num++;
					var index = url_list.length-1; 
					img_section.eq(index).prepend("<tr><td><a href='" + url_list[index] + "'><img src='"+ url_list[index] +"'></a></td></tr>")
					img_section.eq(index).append("<button>DELETE</button>")
					$('.js-upload-photos').attr("style", "visibility: none");
					}
				}
		});
	});


</script>
<!--
<script src="{% static 'closet/js/basic-upload.js' %}"></script>
-->
{% endblock %}

readymade_oatmeal/closet/templates/closet/clothes_info.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}{% endblock %}

{% block content %}
<div>
	<p><img src='{{ clothes.photo.file.url }}'/></p>
	<p>{{ clothes.user }}</p>
	<p>{{ clothes.category }}</p>
	<p>{{ clothes.season }}</p>
	<p>{{ clothes.color }}</p>
	<p>{{ clothes.pattern }}</p>
	<p>{{ clothes.created_at }}</p>
</div>
{% endblock %}

readymade_oatmeal/closet/templates/closet/ootd.html
{% extends "layout.html" %}

{% load static from staticfiles %}
{% block static %}<link rel="stylesheet" href="{% static 'closet/css/ootd.css' %}">{% endblock %}


{% block title %}ootd|{{ block.super }}{% endblock %}


{% block content %}
<div id="outerContainer">
    <div id="ootdcontainer">
        <div class="clothes">
            <div><button class="category_check">CATEGORY</button></div>
            <div class="w3-content w3-display-container">
                {% for piece in clothes %}
                    <img class="mySlides" src='{{ piece.photo.file.url }}'/ style="width:90%">
                {% endfor %}
        
              <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
              <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
            </div>
        </div>
        <div class="clothes">
            <div><button class="category_check">CATEGORY</button></div>
            <div class="left"></div>
            <div class="clothes_container"></div>
            <div class="right"></div>
        </div>
    </div>
</div>
<button>ADD</button>
<input type="submit" value="Save">
{% endblock %}


{% block javascript %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script>
    var container = document.querySelector("#ootdcontainer");
    var activeItem = null;
    var active = false;

    container.addEventListener("touchstart", dragStart, false);
    container.addEventListener("touchend", dragEnd, false);
    container.addEventListener("touchmove", drag, false);

    container.addEventListener("mousedown", dragStart, false);
    container.addEventListener("mouseup", dragEnd, false);
    container.addEventListener("mousemove", drag, false);

    function dragStart(e) {

      if (e.target !== e.currentTarget && e.target.className == 'clothes') {
        active = true;

        // this is the item we are interacting with
        activeItem = e.target;

        if (activeItem !== null) {
          if (!activeItem.xOffset) {
            activeItem.xOffset = 0;
          }

          if (!activeItem.yOffset) {
            activeItem.yOffset = 0;
          }

          if (e.type === "touchstart") {
            activeItem.initialX = e.touches[0].clientX - activeItem.xOffset;
            activeItem.initialY = e.touches[0].clientY - activeItem.yOffset;
          } else {
            console.log("doing something!");
            activeItem.initialX = e.clientX - activeItem.xOffset;
            activeItem.initialY = e.clientY - activeItem.yOffset;
          }
        }
      }
    }

    function dragEnd(e) {
      if (activeItem !== null) {
        activeItem.initialX = activeItem.currentX;
        activeItem.initialY = activeItem.currentY;
      }

      active = false;
      activeItem = null;
    }

    function drag(e) {
      if (active) {
        if (e.type === "touchmove") {
          e.preventDefault();

          activeItem.currentX = e.touches[0].clientX - activeItem.initialX;
          activeItem.currentY = e.touches[0].clientY - activeItem.initialY;
        } else {
          activeItem.currentX = e.clientX - activeItem.initialX;
          activeItem.currentY = e.clientY - activeItem.initialY;
        }

        activeItem.xOffset = activeItem.currentX;
        activeItem.yOffset = activeItem.currentY;

        setTranslate(activeItem.currentX, activeItem.currentY, activeItem);
      }
    }

    function setTranslate(xPos, yPos, el) {
      el.style.transform = "translate3d(" + xPos + "px, " + yPos + "px, 0)";
    }

    $(".category_check").click(
      function(){
        newone = $("<div>diii</div>");
        $('.clothes').append(newone);
      }
    )
   
</script>
<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}
</script>
{% endblock %}